### ISSUE TITLE
TypeError: 'bool' object is not subscriptable

### ISSUE THREAD

**Issue by maxdemajo** [mrrothe/py365#4]
Using Python 3, not sure if this was made for 2.7. Error pops up on running script, configurations set as instructed: 

> Traceback (most recent call last):
  File ".\riskyrules.py", line 110, in <module>
    renderRules()
  File ".\riskyrules.py", line 104, in renderRules
    rulesdata = getAllRules()
  File ".\riskyrules.py", line 77, in getAllRules
    output.append(getRuleRisk(rule, user["userPrincipalName"]))
  File ".\riskyrules.py", line 95, in getRuleRisk
    risk += factor.calculateRisk(rule, user)
  File ".\riskyrules.py", line 30, in calculateRisk
    if isinstance(actionValue[0], dict):
TypeError: 'bool' object is not subscriptable

**Comment by mrrothe** [comment]
It's definitely Python3 - I've added a check to that method now so it will only try and reference the first item if it is a list
https://github.com/mrrothe/py365/commit/07e87185d6bd38028ad03941df971acd0468b15c#diff-2a3d04dcf39ad8cba483067b3ccddd3d
Let me know if that resolves it.

**Comment by maxdemajo** [comment]
That got it, works great now thanks!
